image: openbsd/latest
packages:
  - hugo-0.116.1-extended
sources:
  - git@git.sr.ht:~cr4sh0v3rrid3/blog
environment:
  deploy: _srht@sigkill.no
secrets:
  # You'll want to replace this with the ID of your secret copied above
  - 3b1ce6db-ec1a-480b-83d2-634001128912
tasks:
  - setup: |
      ftp https://github.com/gohugoio/hugo/releases/download/v0.124.1/hugo_0.124.1_openbsd-amd64.tar.gz
      tar xvzf hugo_0.124.1_openbsd-amd64.tar.gz
      mkdir bin
      mv hugo bin/
      cd blog
  - build: |
      cd blog
      hugo --config hugo.toml
  - deploy: |
      cd blog
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -rP public $deploy:/var/www/sigkill.no/
