baseURL = "https://sigkill.no"
copyright = "cr4sh0v3rrid3 (CC BY 4.0)"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

[markup.highlight]
  lineNos = true
  lineNumbersInTable = false
  noClasses = false

[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2

[languages.en]
  title = "SIGKILL"
  label = "English"
  locale = "en-US"
  contentDir = "content"

[params]
  description = "An independent corner of the internet. Notes on Unix, networks, and things figured out along the way."

[params.author]
  name = "cr4sh0v3rrid3"
  email = "cr4sh@sigkill.no"
